version: "3.7"
services:
  art-api:
    container_name: art-api
    build:
      dockerfile: php.Dockerfile
      context: .
    restart: always
    volumes:
      - ".:/var/www/html/"
      - "./container/php/xdebug-local.ini:/usr/local/etc/php/conf.d/xdebug-local.ini"
      - "./container/apache2/000-default.conf:/etc/apache2/sites-available/000-default.conf"
    ports:
      - "85:80"
      - "5173:5173"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  art-db:
    container_name: art-db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - 'art-db:/var/lib/mysql'
    environment:
      MYSQL_DATABASE: art_api
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3311:3306"
volumes:
  art-db:
